sudo: false
language: node_js
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+$/
node_js:
- '6'
- '8'
script: npm run test
deploy:
  provider: npm
  email: mitmaro@gmail.com
  api_key:
    secure: mGwfUlaIz5kYO7UCV0fPNjkbJuuZ36eHdy7e7rideOB9ogPDlMnZ6hy0KB65Ks/e/LyqSohdf6f5EZop9WLgmo/ZA4yhTbzw6YieU9J358kR1rC4PWbk2dtSEQLEf9xoiy2suDL35CXfnBtlfgca/FD4JzE8LO8tozoog+myvezsF6Cj8m6m20KABGTgRGtU6w2Ocn5LFm8lJmE4NnKXhg0NTSgYDZkzTZOpBdnFXanrygRh8Q4U7l/I7VlYKDnmMAY3fo9C+tLgMw0t5HILW0dpUtvaCD4VdzPvVYqmjD4Ql1zW5A2yKd2IV+L7NAjS6fRkZDeLl96DK8z/pKuV5YieALI1xVbxBGygfmOXA45qsXylxos6pLN0ebq42gXcyAUdp2WWV28KxjhmjLPKUwZdprjhDxfXDsDZN2CIj238fsSCOw7SzjViJ413rOH5ngGZ62tL7YO23bwWSC7hKI15BiNFH2gbAR5xk7oUueMBy23MJtNsFRpqQ8JCQqEcwFP9aAbPTr5fCvaO13/b3behaDKjZnifMylcWJm3LWSthM5XAnt5rdLhfa+sMqONfJQfbtQiEx8KpJFniNpgtZK6qV+L4NO75tipGrFrc2NB+6dwEqrOfeM3juhZxzZUcwHEsnlMEGU3EDcEdDP1uzM00Y2Hs/SNOliqXwQguug=
  on:
    tags: true
    repo: MitMaro/mitmaro-build-scripts
